insert into users(user_id,name,password,money,status) values ("ozllzlu" , "김예진" , "7777" , 10000 ,"관리자")
insert into users(user_id,name,password,money,status) values ("ozllzlu2" , "김예지" , "7777" , 10000 ,"손님")
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (1,"신라면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (2,"불닭볶음면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (3,"진라면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (4,"짜파게티",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (5,"너구리",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (6,"참깨라면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (7,"비빔면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (8,"안성탕면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (9,"진짬뽕",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (10,"틈새라면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (11,"삼양라면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (13,"열라면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (14,"스낵면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (15,"꼬꼬면",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (16,"하오하오",10,3000)
insert into menu(menu_id,menu_name,menu_amount,menu_price) values (17,"공깃밥",10,1000)