insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (1,'신라면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (2,'불닭볶음면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (3,'진라면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (4,'짜파게티',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (5,'너구리',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (6,'참깨라면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (7,'비빔면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (8,'안성탕면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (9,'진짬뽕',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (10,'틈새라면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (11,'삼양라면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (12,'열라면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (13,'스낵면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (14,'꼬꼬면',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (15,'하오하오',10,3000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (16,'공깃밥',10,1000,'라면');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (17,'레몬에이드',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (18,'체리에이드',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (19,'아이스믹스커피',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (20,'미숫가루',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (21,'복숭아녹차',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (22,'레몬녹차',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (23,'토레타',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (24,'웰치스포도',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (25,'몬스터울트라',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (26,'코코팜복숭아',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (27,'포카리스웨트',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (28,'파워에이드',10,2000,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (29,'마운틴듀',10,1500,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (30,'콜라',10,1500,'음료');
insert into menu(menu_id,menu_name,menu_amount,menu_price,menu_kind) values (31,'사이다',10,1500,'음료');
insert into users(user_no, user_id, name, password, money, status) values (1, 'ozllzlu' , '김예진' , '7777' , 10000 ,'관리자');
insert into users(user_no, user_id, name, password, money, status) values (2, 'ozllzlu2' , '김예지' , '7777' , 10000 ,'손님');
insert into users(user_no, user_id, name, password, money, status) values (3, 'wecky' , '웨키' , '7777' , 5000 ,'손님');
insert into users(user_no, user_id, name, password, money, status) values (4, 'etorn0', 'Ernestine', 531, 27493, '손님');
insert into users(user_no, user_id, name, password, money, status) values (5, 'fpemberton1', 'Frasquito', 664, 36275, '손님');
insert into users(user_no, user_id, name, password, money, status) values (6, 'tgillbard2', 'Tabbie', 796, 39546, '손님');
insert into users(user_no, user_id, name, password, money, status) values (7, 'mwalls3', 'Marlane', 729, 37995, '손님');
insert into users(user_no, user_id, name, password, money, status) values (8, 'jshewen4', 'Jyoti', 743, 31272, '손님');
insert into users(user_no, user_id, name, password, money, status) values (9, 'sdigance5', 'Sol', 291, 24015, '손님');
insert into users(user_no, user_id, name, password, money, status) values (10, 'wplewright6', 'Wheeler', 338, 6002, '손님');
insert into users(user_no, user_id, name, password, money, status) values (11, 'ailyuchyov7', 'Allan', 167, 18389, '손님');
insert into users(user_no, user_id, name, password, money, status) values (12, 'mhonacker8', 'Merilyn', 272, 48476, '손님');
insert into users(user_no, user_id, name, password, money, status) values (13, 'mwillson9', 'Marlo', 499, 36111, '손님');
insert into users(user_no, user_id, name, password, money, status) values (14, 'kbramforda', 'Kirstyn', 802, 28795, '손님');
insert into users(user_no, user_id, name, password, money, status) values (15, 'scullingfordb', 'Siusan', 645, 28260, '손님');
insert into users(user_no, user_id, name, password, money, status) values (16, 'rmilnec', 'Rozelle', 343, 12086, '손님');
insert into users(user_no, user_id, name, password, money, status) values (17, 'nhaysomd', 'Neil', 655, 5182, '손님');
insert into users(user_no, user_id, name, password, money, status) values (18, 'dguyse', 'Duane', 320, 4863, '손님');
insert into users(user_no, user_id, name, password, money, status) values (19, 'nmacpeicef', 'Neal', 512, 26760, '손님');
insert into users(user_no, user_id, name, password, money, status) values (20, 'stompkissg', 'Sallee', 693, 5667, '손님');
insert into users(user_no, user_id, name, password, money, status) values (21, 'ksheadh', 'Kin', 670, 20021, '손님');
insert into users(user_no, user_id, name, password, money, status) values (22, 'karmfirldi', 'Kylynn', 931, 33647, '손님');
insert into users(user_no, user_id, name, password, money, status) values (23, 'ahaythornj', 'Arlene', 546, 48122, '손님');
insert into users(user_no, user_id, name, password, money, status) values (24, 'lpeschetk', 'Luz', 774, 21107, '손님');
insert into users(user_no, user_id, name, password, money, status) values (25, 'ajessl', 'Annamarie', 811, 22325, '손님');
insert into users(user_no, user_id, name, password, money, status) values (26, 'aawcockm', 'Alanna', 765, 33270, '손님');
insert into users(user_no, user_id, name, password, money, status) values (27, 'gcolloughn', 'Garfield', 939, 48536, '손님');
insert into users(user_no, user_id, name, password, money, status) values (28, 'gdavereno', 'Gareth', 437, 33124, '손님');
insert into users(user_no, user_id, name, password, money, status) values (29, 'sgronop', 'Shelby', 230, 25865, '손님');
insert into users(user_no, user_id, name, password, money, status) values (30, 'scuredellq', 'Somerset', 108, 40913, '손님');
insert into users(user_no, user_id, name, password, money, status) values (31, 'cbarockr', 'Colver', 497, 28629, '손님');
insert into users(user_no, user_id, name, password, money, status) values (32, 'tminithorpes', 'Theo', 212, 23381, '손님');
insert into users(user_no, user_id, name, password, money, status) values (33, 'emariat', 'Elsbeth', 439, 43613, '손님');
insert into users(user_no, user_id, name, password, money, status) values (34, 'oswayslandu', 'Opaline', 699, 31292, '손님');
insert into users(user_no, user_id, name, password, money, status) values (35, 'jhaysomv', 'Jeralee', 510, 27276, '손님');
insert into users(user_no, user_id, name, password, money, status) values (36, 'rpelew', 'Roshelle', 998, 17684, '손님');
insert into users(user_no, user_id, name, password, money, status) values (37, 'zmarkushkinx', 'Zorah', 869, 45578, '손님');
insert into users(user_no, user_id, name, password, money, status) values (38, 'mdallimorey', 'Minna', 257, 33070, '손님');
insert into users(user_no, user_id, name, password, money, status) values (39, 'jbrunkez', 'Jamima', 641, 7223, '손님');
insert into users(user_no, user_id, name, password, money, status) values (40, 'saprahamian10', 'Sasha', 965, 21063, '손님');
insert into users(user_no, user_id, name, password, money, status) values (41, 'pvigus11', 'Pincas', 368, 49784, '손님');
insert into users(user_no, user_id, name, password, money, status) values (42, 'mlafferty12', 'Martelle', 129, 15526, '손님');
insert into users(user_no, user_id, name, password, money, status) values (43, 'sgraber13', 'Samuele', 925, 4844, '손님');
insert into users(user_no, user_id, name, password, money, status) values (44, 'vflowerden14', 'Valerie', 544, 46578, '손님');
insert into users(user_no, user_id, name, password, money, status) values (45, 'bmungin15', 'Bentley', 774, 3908, '손님');
insert into users(user_no, user_id, name, password, money, status) values (46, 'lhysom16', 'Latisha', 398, 39941, '손님');
insert into users(user_no, user_id, name, password, money, status) values (47, 'nephgrave17', 'Nerti', 895, 29373, '손님');
insert into users(user_no, user_id, name, password, money, status) values (48, 'ccroome18', 'Chantalle', 160, 6875, '손님');
insert into users(user_no, user_id, name, password, money, status) values (49, 'cwarrell19', 'Chantalle', 871, 34752, '손님');
insert into users(user_no, user_id, name, password, money, status) values (50, 'fhowsam1a', 'Fowler', 697, 34529, '손님');
insert into users(user_no, user_id, name, password, money, status) values (51, 'kmctavy1b', 'Kristian', 390, 38686, '손님');
insert into users(user_no, user_id, name, password, money, status) values (52, 'sgolde1c', 'Sayre', 203, 30758, '손님');
insert into users(user_no, user_id, name, password, money, status) values (53, 'craleston1d', 'Cordula', 577, 46303, '손님');
insert into users(user_no, user_id, name, password, money, status) values (54, 'gdwelley1e', 'Griff', 137, 8669, '손님');
insert into users(user_no, user_id, name, password, money, status) values (55, 'abarta1f', 'Abe', 752, 26737, '손님');
insert into users(user_no, user_id, name, password, money, status) values (56, 'tfarncombe1g', 'Tim', 524, 22008, '손님');
insert into users(user_no, user_id, name, password, money, status) values (57, 'bmityashin1h', 'Biron', 606, 24210, '손님');
insert into users(user_no, user_id, name, password, money, status) values (58, 'lboxell1i', 'Lawton', 790, 13019, '손님');
insert into users(user_no, user_id, name, password, money, status) values (59, 'hescolme1j', 'Huberto', 109, 48116, '손님');
insert into users(user_no, user_id, name, password, money, status) values (60, 'btrengove1k', 'Brigitte', 448, 38718, '손님');
insert into users(user_no, user_id, name, password, money, status) values (61, 'hchaney', 'Haroun', 336, 35254, '손님');
insert into users(user_no, user_id, name, password, money, status) values (62, 'nmoorey1m', 'Naoma', 407, 9633, '손님');
insert into users(user_no, user_id, name, password, money, status) values (63, 'tdanter1n', 'Tamarra', 777, 23890, '손님');
insert into users(user_no, user_id, name, password, money, status) values (64, 'ngaythwaite1o', 'Nathanial', 149, 42453, '손님');
insert into users(user_no, user_id, name, password, money, status) values (65, 'sselman1p', 'Sloan', 726, 31823, '손님');
insert into users(user_no, user_id, name, password, money, status) values (66, 'odepietri1q', 'Obadiah', 970, 33440, '손님');
insert into users(user_no, user_id, name, password, money, status) values (67, 'fmitchener1r', 'Frances', 520, 24698, '손님');
insert into users(user_no, user_id, name, password, money, status) values (68, 'aagiolfinger1s', 'Ancell', 811, 14130, '손님');
insert into sell(id, user_no, menu_id, sell_amount) values (1, 1, 2, 2);
insert into sell(id, user_no, menu_id, sell_amount) values (2, 2, 4, 1);
insert into sell(id, user_no, menu_id, sell_amount) values (3, 3, 15, 3);
